# -*- coding: utf-8 -*-
"""RL using MC and SARSA

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1apIhszPfpbAVIkP_6FPnkw8uXysWeCbk
"""

import gymnasium as gym
import numpy as np
import time
from gymnasium.envs.registration import register, registry
from gymnasium.envs.toy_text.frozen_lake import generate_random_map

# Register custom environments
def register_custom_envs():
    if "CustomFrozenLake-v1" in registry:
        del registry["CustomFrozenLake-v1"]
    if "ExpandedFrozenLake-v1" in registry:
        del registry["ExpandedFrozenLake-v1"]

    custom_map = generate_random_map(size=100)

    register(
        id="CustomFrozenLake-v1",
        entry_point="gymnasium.envs.toy_text:FrozenLakeEnv",
        kwargs={"desc": custom_map, "is_slippery": False},
        max_episode_steps=10000,
    )

    class ExpandedFrozenLake(gym.envs.toy_text.FrozenLakeEnv):
        def __init__(self, **kwargs):
            super().__init__(**kwargs)
            self.action_space = gym.spaces.Discrete(5)
            for state in self.P:
                teleport_target = self.np_random.integers(0, self.observation_space.n)
                self.P[state][4] = [(1.0, teleport_target, 0.0, False)]

        def step(self, action):
            if action == 4:
                self.s = self.np_random.integers(0, self.observation_space.n)
                return self.s, 0.0, False, False, {}
            return super().step(action)

    register(
        id="ExpandedFrozenLake-v1",
        entry_point=lambda **kwargs: ExpandedFrozenLake(**kwargs),
        kwargs={"desc": custom_map, "is_slippery": False},
        max_episode_steps=10000,
    )

# Value Iteration
def value_iteration(env, discount=0.99, threshold=1e-8):
    transition_probs = env.unwrapped.P
    num_states = env.observation_space.n
    num_actions = env.action_space.n

    value_function = np.zeros(num_states)
    policy = np.zeros(num_states, dtype=int)

    while True:
        delta = 0
        for state in range(num_states):
            action_values = np.zeros(num_actions)
            for action in range(num_actions):
                for prob, next_state, reward, done in transition_probs[state][action]:
                    action_values[action] += prob * (reward + discount * value_function[next_state])
            best_action = np.argmax(action_values)
            delta = max(delta, abs(action_values[best_action] - value_function[state]))
            value_function[state] = action_values[best_action]
            policy[state] = best_action
        if delta < threshold:
            break
    return policy

# Policy Iteration
def policy_iteration(env, discount=0.99, threshold=1e-8):
    transition_probs = env.unwrapped.P
    num_states = env.observation_space.n
    num_actions = env.action_space.n

    policy = np.random.choice(num_actions, size=num_states)
    value_function = np.zeros(num_states)

    while True:
        while True:
            delta = 0
            for state in range(num_states):
                action = policy[state]
                new_value = sum(prob * (reward + discount * value_function[next_state])
                                for prob, next_state, reward, done in transition_probs[state][action])
                delta = max(delta, abs(new_value - value_function[state]))
                value_function[state] = new_value
            if delta < threshold:
                break

        policy_stable = True
        for state in range(num_states):
            old_action = policy[state]
            action_values = np.zeros(num_actions)
            for action in range(num_actions):
                for prob, next_state, reward, done in transition_probs[state][action]:
                    action_values[action] += prob * (reward + discount * value_function[next_state])
            best_action = np.argmax(action_values)
            policy[state] = best_action
            if old_action != best_action:
                policy_stable = False
        if policy_stable:
            break
    return policy

# Q-Learning
def q_learning(env, discount=0.99, alpha=0.1, epsilon=0.1, episodes=10000):
    num_states = env.observation_space.n
    num_actions = env.action_space.n

    Q = np.zeros((num_states, num_actions))

    for _ in range(episodes):
        state, _ = env.reset()
        done = False

        while not done:
            if np.random.rand() < epsilon:
                action = np.random.choice(num_actions)
            else:
                action = np.argmax(Q[state])

            next_state, reward, terminated, truncated, _ = env.step(action)
            done = terminated or truncated

            best_next_action = np.argmax(Q[next_state])
            td_target = reward + discount * Q[next_state, best_next_action]
            Q[state, action] += alpha * (td_target - Q[state, action])

            state = next_state

    policy = np.argmax(Q, axis=1)
    return policy

# Monte Carlo Control
def monte_carlo(env, discount=0.99, epsilon=0.1, episodes=10000):
    num_states = env.observation_space.n
    num_actions = env.action_space.n
    Q = np.zeros((num_states, num_actions))
    returns = [[[] for _ in range(num_actions)] for _ in range(num_states)]

    for _ in range(episodes):
        state, _ = env.reset()
        episode = []
        done = False

        while not done:
            if np.random.rand() < epsilon:
                action = np.random.choice(num_actions)
            else:
                action = np.argmax(Q[state])
            next_state, reward, terminated, truncated, _ = env.step(action)
            episode.append((state, action, reward))
            state = next_state
            done = terminated or truncated

        G = 0
        visited = set()
        for t in reversed(range(len(episode))):
            s, a, r = episode[t]
            G = discount * G + r
            if (s, a) not in visited:
                visited.add((s, a))
                returns[s][a].append(G)
                Q[s, a] = np.mean(returns[s][a])

    policy = np.argmax(Q, axis=1)
    return policy

# SARSA
def sarsa(env, discount=0.99, alpha=0.1, epsilon=0.1, episodes=10000):
    num_states = env.observation_space.n
    num_actions = env.action_space.n
    Q = np.zeros((num_states, num_actions))

    for _ in range(episodes):
        state, _ = env.reset()
        if np.random.rand() < epsilon:
            action = np.random.choice(num_actions)
        else:
            action = np.argmax(Q[state])
        done = False

        while not done:
            next_state, reward, terminated, truncated, _ = env.step(action)
            done = terminated or truncated

            if np.random.rand() < epsilon:
                next_action = np.random.choice(num_actions)
            else:
                next_action = np.argmax(Q[next_state])

            td_target = reward + discount * Q[next_state, next_action]
            Q[state, action] += alpha * (td_target - Q[state, action])

            state, action = next_state, next_action

    policy = np.argmax(Q, axis=1)
    return policy

# Policy Evaluation
def evaluate_policy(env, policy, episodes=100):
    total_rewards = []
    for _ in range(episodes):
        state, _ = env.reset()
        done = False
        reward_sum = 0
        while not done:
            action = policy[state]
            state, reward, terminated, truncated, _ = env.step(action)
            done = terminated or truncated
            reward_sum += reward
        total_rewards.append(reward_sum)
    return np.mean(total_rewards)

# Run all algorithms on environments
def run_all():
    register_custom_envs()
    envs = {
        "Original FrozenLake": gym.make("FrozenLake-v1", map_name="8x8", is_slippery=False),
        "Custom FrozenLake": gym.make("CustomFrozenLake-v1"),
        "Expanded FrozenLake": gym.make("ExpandedFrozenLake-v1"),
    }

    for name, env in envs.items():
        print(f"\n Running on {name}")

        pi_vi = value_iteration(env)
        print(f"  Value Iteration Avg Reward: {evaluate_policy(env, pi_vi):.3f}")

        pi_pi = policy_iteration(env)
        print(f"  Policy Iteration Avg Reward: {evaluate_policy(env, pi_pi):.3f}")

        pi_ql = q_learning(env)
        print(f"  Q-Learning Avg Reward: {evaluate_policy(env, pi_ql):.3f}")

        pi_mc = monte_carlo(env)
        print(f"  Monte Carlo Avg Reward: {evaluate_policy(env, pi_mc):.3f}")

        pi_sarsa = sarsa(env)
        print(f"  SARSA Avg Reward: {evaluate_policy(env, pi_sarsa):.3f}")

if __name__ == "__main__":
    run_all()